-----------------| USER |-----------------

CREATE SEQUENCE SEQ_USER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_USER (
    USER_ID NUMBER(19,0) NOT NULL,
    ACTIVE NUMBER(1,0) DEFAULT 0 CHECK (ACTIVE BETWEEN 0 AND 1) NOT NULL,
    EMAIL VARCHAR2(255 CHAR) NOT NULL,
    NAME VARCHAR2(255 CHAR) NOT NULL,
    PASSWORD VARCHAR2(255 CHAR) NOT NULL,
    ROLE VARCHAR2(10 CHAR) NOT NULL,
    PRIMARY KEY (USER_ID)
);

INSERT INTO
    TBL_USER
        (USER_ID, ACTIVE, EMAIL, NAME, PASSWORD, ROLE)
    VALUES
        (1, 1, 'admin@admin.com', 'System Administrator', '$2a$10$dxlL.53a1jUX4Zee3E1scuXYLG8Zg.4qydFVlcIzSDsitcd900OKC', 'ADMIN');
-- Password '1234abcd' after encrypt


-----------------| AREA |-----------------

CREATE SEQUENCE SEQ_AREA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_AREA (
    AREA_ID NUMBER(19,0) NOT NULL,
    DESCRIPTION VARCHAR2(255 CHAR),
    LOCATION VARCHAR2(255 CHAR),
    AREA_SIZE VARCHAR2(255 CHAR),
    PRIMARY KEY (AREA_ID)
);

-----------------| NOTIFICATION |-----------------

CREATE SEQUENCE SEQ_NOTIFICATION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_NOTIFICATION (
    NOTIFICATION_ID NUMBER(19,0) NOT NULL,
    DESCRIPTION VARCHAR2(255 CHAR),
    TIMESTAMP TIMESTAMP(6),
    SENSOR_ID NUMBER(19,0),
    PRIMARY KEY (NOTIFICATION_ID)
);

-----------------| SENSOR |-----------------

CREATE SEQUENCE SEQ_SENSOR
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_SENSOR (
    SENSOR_ID NUMBER(19,0) NOT NULL,
    LOCATION VARCHAR2(255 CHAR),
    TYPE VARCHAR2(255 CHAR),
    AREA_ID NUMBER(19,0),
    PRIMARY KEY (SENSOR_ID)
);

-----------------| WEATHER |-----------------

CREATE SEQUENCE SEQ_WEATHER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_WEATHER (
    WEATHER_ID NUMBER(19,0) NOT NULL,
    DESCRIPTION VARCHAR2(255 CHAR),
    HUMIDITY NUMBER(10,0),
    TEMPERATURE NUMBER(10,0),
    TIMESTAMP TIMESTAMP(6),
    SENSOR_ID NUMBER(19,0),
    PRIMARY KEY (WEATHER_ID)
);

-----------------| SCHEDULE |-----------------

CREATE SEQUENCE SEQ_SCHEDULE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_SCHEDULE (
    SCHEDULE_ID NUMBER(19,0) NOT NULL,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    PRIMARY KEY (SCHEDULE_ID)
);

-----------------| FK CONSTRAINTS |-----------------

ALTER TABLE TBL_NOTIFICATION
    ADD CONSTRAINT FK_NOTIFICATION_SENSOR_ID
        FOREIGN KEY (SENSOR_ID)
            REFERENCES TBL_SENSOR;

ALTER TABLE TBL_SENSOR
    ADD CONSTRAINT FK_SENSOR_AREA_ID
        FOREIGN KEY (AREA_ID)
            REFERENCES TBL_AREA;

ALTER TABLE TBL_WEATHER
    ADD CONSTRAINT FK_WEATHER_SENSOR_ID
        FOREIGN KEY (SENSOR_ID)
            REFERENCES TBL_SENSOR;